mom_cli.impl=net.echinopsii.ariane.community.core.messaging.rabbitmq.Client
mom_cli.rabbitmq.product=Ariane
mom_cli.rabbitmq.information=Ariane Injector Remote Messaging Service
mom_cli.rabbitmq.copyright=AGPLv3
mom_cli.rabbitmq.version=##MCLI_RBQ_VERSION
mom_host.fqdn=##MHOST_FQDN
mom_host.port=##MHOST_PORT
mom_host.user=##MHOST_USER
mom_host.password=##MHOST_PASSWD
mom_host.rbq_vhost=##MHOST_VHOST
ariane.pgurl=http://##ARIANE_FQDN:6969/ariane
ariane.osi=##ARIANE_HOST
ariane.otm=##ARIANE_OPS_TEAM
ariane.app=Ariane
ariane.cmp=echinopsii
